magazyn/config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root 'panel#index'

  resources :panel, only: [:index]
  resources :groups, except: [:show]
  resources :tools, except: [:show]
  resources :users, except: [:show]
  post 'add_user_group' => 'users#add_user_group', as: 'add_user_group'

  post 'change_tools_admin' => 'tools#change_tools_admin', as: 'change_tools_admin'
  post 'taken_tools' => 'tools#taken_tools', as: 'taken_tools'
  get 'history' => 'panel#history', as: 'history'


end

magazyn/app/models/added_tool.rb
class AddedTool < ActiveRecord::Base
  belongs_to :tool

  validates :tool_id, :count, presence: :true
end

magazyn/app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable :registerable, :recoverable
  devise :database_authenticatable, :rememberable, :trackable, :validatable
end

magazyn/app/models/group.rb
class Group < ActiveRecord::Base
  has_many :taken_tools
  has_many :users

  validates :name, presence: :true
end

magazyn/app/models/taken_tool.rb
class TakenTool < ActiveRecord::Base
  belongs_to :tool
  belongs_to :group

  validates :tool_id, :count, presence: :true
end

magazyn/app/models/tool.rb
class Tool < ActiveRecord::Base
  has_many :taken_tools

  validates :name, :price, :count, :code, presence: :true

  def can_take(how_many)
    return self.count-how_many > -1
  end
end

magazyn/app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :group

  validates :name, :surname, presence: :true

  def add_to_group(gid)
      self.group_id = gid
  end
end

magazyn/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

magazyn/app/controllers/groups_controller.rb
class GroupsController < ApplicationController
# before_action :authenticate_admin!

  def index
    @groups = Group.all.order('created_at DESC')
    @group = Group.new
  end

  def edit
    @group=Group.find(params[:id])
  end

  def update
    @group =Group.find(params[:id])  
    @group.name = params[:group][:name]
    if @group.save
      redirect_to groups_path, notice: "Edytowano"
    else
      redirect_to groups_path, notice: "Blad"
    end
  end
  
  def new
    @group=Group.new
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to groups_path, notice: "Utworzono"
    else
      redirect_to groups_path, notice: "Blad"
    end
  end

  def destroy
    if Group.find(params[:id]).destroy
      redirect_to groups_path notice: "Usunieto"
    else
      redirect_to groups_path notice: "Nie usunieto"
    end
  end

  def group_params
    params.require(:group).permit(:name)
  end

end

magazyn/app/controllers/panel_controller.rb
class PanelController < ApplicationController
# before_action :authenticate_admin!

  def index
    @groups = Group.all
    @tools = Tool.where(active: true)
  end

  def history
    @history = TakenTool.all + AddedTool.all
  end
end

magazyn/app/controllers/tools_controller.rb
class ToolsController < ApplicationController
# before_action :authenticate_admin!

  def index
    @tools = Tool.where(active: true).order('created_at DESC')
    @tool = Tool.new
    @add = AddedTool.new
    @take = TakenTool.new
  end

  def edit
    @tool=Tool.find(params[:id])
  end

  def update
    @tool =Tool.find(params[:id])  
    @tool.name = params[:tool][:name]
    @tool.code = params[:tool][:code]
    @tool.count = params[:tool][:count]
    @tool.price = params[:tool][:price]
    if @tool.save
      redirect_to tools_path, notice: "Edytowano "+@tool.name+' '+@tool.code
    else
      redirect_to tools_path, notice: "Blad w edycji"+@tool.name+' '+@tool.code
    end
  end
  
  def new
    @tool=Tool.new
  end

  def create
    @tool = Tool.new(tool_params)
    if @tool.save
      AddedTool.create(tool_id: @tool.id, count: @tool.count)
      redirect_to tools_path, notice: "Utworzono "+@tool.name+' '+@tool.code
    else
      redirect_to tools_path, notice: "Blad w tworzeniu"+@tool.name+' '+@tool.code
    end
  end

  def destroy
    Tool.find(params[:id]).update(active: false)
    @tool = Tool.find(params[:id])
    if @tool.active
      redirect_to tools_path, notice: "Nie usunieto "+@tool.name+' '+@tool.code
    else
      redirect_to tools_path, notice: "Usunieto "+@tool.name+' '+@tool.code
    end
  end

  def change_tools_admin
    if params[:desc] == '+'
      AddedTool.create(tool_id: params[:tool_id], count: params[:count])
      c = Tool.find(params[:tool_id])
      Tool.find(params[:tool_id]).update(count: c.count + params[:count].to_i)
      redirect_to tools_path, notice: 'Zmieniono '+c.name+' '+c.code+' o +'+params[:count]
    else
      TakenTool.create(tool_id: params[:tool_id], count: params[:count])
      c = Tool.find(params[:tool_id])
      if c.count - params[:count].to_i > -1
        Tool.find(params[:tool_id]).update(count: c.count - params[:count].to_i)
        redirect_to tools_path, notice: 'Zmieniono '+c.name+' '+c.code+' o -'+params[:count]
      else
        redirect_to tools_path, notice: 'Nie ma tylu sztuk '+c.name+' '+c.code
      end
    end
  end

  def taken_tools
    if Tool.find(params[:tool_id]).can_take(params[:count].to_i)
      TakenTool.create(group_id: params[:group_id], tool_id: params[:tool_id], count: params[:count])
      c = Tool.find(params[:tool_id])
      Tool.find(params[:tool_id]).update(count: c.count - params[:count].to_i)
      redirect_to root_path, notice: 'Wydano '+params[:count]+' sztuk '+c.name+' '+c.code+' grupie '+Group.find(params[:group_id]).name
    else
      redirect_to root_path, notice: 'Nie ma tylu sztuk w magaynie'
    end
  end

  private

  def tool_params
    params.require(:tool).permit(:name, :count, :code, :price)
  end
end

magazyn/app/controllers/users_controller.rb
class UsersController < ApplicationController
# before_action :authenticate_admin!

  def index
    @users = User.all.order('created_at DESC')
    @user = User.new
    @groups = Group.all
  end

  def edit
    @user=User.find(params[:id])
    @groups = Group.all
  end

  def update
    @user =User.find(params[:id])  
    @user.name = params[:user][:name]
    @user.surname = params[:user][:surname]
    unless params[:user][:group_id] == ''
      @user.group = Group.find(params[:user][:group_id])
    else
      @user.group = nil
    end
    if @user.save
      redirect_to users_path, notice: "Edytowano "+@user.name+@user.surname
    else
      redirect_to users_path, notice: "Blad w edycji "+@user.name+@user.surname
    end
  end
  
  def new
    @user=User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_path, notice: "Utworzono "+@user.name+' '+@user.surname
    else
      redirect_to users_path, notice: "Blad w tworzeniu "+@user.name+' '+@user.surname
    end
  end

  def destroy
    user = User.find(params[:id])
    if user.destroy
      redirect_to users_path, notice: "Usunieto "+user.name+' '+user.surname
    else
      redirect_to users_path, notice: "Nie usunieto "+user.name+' '+user.surname
    end
  end

  def user_params
    params.require(:user).permit(:name, :surname, :group_id)
  end

  def add_user_group
    u = User.find(params[:user])
    u.add_to_group(params[:group])
    if u.save
      redirect_to users_path, notice: 'Dodano do grupy '+u.name+' '+u.surname
    else
      redirect_to users_path, notice: 'Blad w dodawaniu '+u.name+' '+u.surname
    end
  end

end

magazyn/app/helpers/application_helper.rb
module ApplicationHelper
end

magazyn/app/views/groups/edit.html.haml
=form_for @group do |p|
  .form-group
    =p.label 'Nazwa'
    =p.text_field :name, class: 'form-control'
  .form-group
    =submit_tag "Edytuj", class: "btn btn-primary"

magazyn/app/views/groups/index.html.haml
#show_add
  %a{href: '#'}
    Dodaj Grupę
.add
  =form_tag groups_path, multipart: true do 
    =fields_for @group do |p|
      .row
        .col-lg-4

        .col-lg-4
          .form-group
            =p.label 'Nazwa'
            =p.text_field :name, class: 'form-control'
          .form-group
          =submit_tag "Dodaj", class: "btn btn-primary"
%table#group.row-border.hover
  %thead
    %tr
      %th Nazwa
      %th Ludzie
      %th Data powstania
      %th 
  %tbody
    -@groups.each do |g|
      %tr
        %td
          =g.name
        %td
          -if g.users.count > 0
            -g.users.each do |u|
              %div
                =u.name
                =u.surname
          -elsif g.users.count == 1
            %div
              =g.users.first.name
              =g.users.first.surname
          -else
            Brak
        %td
          =g.created_at.to_date
        %td
          =link_to 'Edytuj', edit_group_path(g.id)
          =link_to 'Usuń', group_path(g.id), method: :delete, data: { confirm: "Napewno chcesz usunąć?" }

:javascript
  $(function(){
    add();
  })
:javascript
  data_table_init_order = [0,'asc'];

magazyn/app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Magazyn
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    -unless controller.class.name.include? 'Devise'
      %nav.navbar.navbar-inverse.navbar-fixed-top
        %ul.nav.navbar-nav
          %li
            =link_to 'Strona Glowna', root_url
          %li
            =link_to 'Grupy', groups_path
          %li
            =link_to 'Użytkownicy', users_path
          %li
            =link_to 'Przedmioty', tools_path
          %li
            =link_to 'Historia', history_path
    .main-container
      -if flash[:notice]
        .notice
          =flash[:notice]
      = yield

magazyn/app/views/panel/history.html.haml
-if @history.count > 0
  %table#group.row-border.hover
    %thead
      %tr
        %th Kto
        %th Numer
        %th Nazwa
        %th Zmiana stanu
        %th Data
    %tbody
      -@history.each do |h|
        %tr
          -if h.class == AddedTool
            -unless h.tool.active
              %td.added_tool{style: "color: yellow;"}
                .deleted
                  Administrator
              %td.added_tool
                .deleted
                  =h.tool_id
              %td.added_tool
                .deleted
                  =h.tool.name
              %td.added_tool
                .deleted
                  =h.count
                  (
                  =h.tool.price * h.count
                  zł)
              %td.added_tool
                .deleted
                  =h.created_at.to_formatted_s(:db)
            -else
              %td.added_tool{style: "color: yellow;"}
                Administrator
              %td.added_tool
                =h.tool_id
              %td.added_tool
                =h.tool.name
              %td.added_tool
                =h.count
                (
                =h.tool.price * h.count
                zł)
              %td.added_tool
                =h.created_at.to_formatted_s(:db)
          -else
            -if h.group_id
              -unless h.tool.active
                %td.taken_tool
                  .deleted
                    =h.group.name
                %td.taken_tool
                  .deleted
                    =h.tool_id
                %td.taken_tool
                  .deleted
                    =h.tool.name
                %td.taken_tool
                  .deleted
                    =h.count
                    (
                    =h.tool.price * h.count
                    zł)
                %td.taken_tool
                  .deleted
                    =h.created_at.to_formatted_s(:db)
              -else
                %td.taken_tool
                  =h.group.name
                %td.taken_tool
                  =h.tool_id
                %td.taken_tool
                  =h.tool.name
                %td.taken_tool
                  =h.count
                  (
                  =h.tool.price * h.count
                  zł)
                %td.taken_tool
                  =h.created_at.to_formatted_s(:db)
            -else
              -unless h.tool.active
                %td.taken_tool{style: "color: yellow;"}
                  .deleted
                    Administrator
                %td.taken_tool
                  .deleted
                    =h.tool_id
                %td.taken_tool
                  .deleted
                    =h.tool.name
                %td.taken_tool
                  .deleted
                    =h.count
                    (
                    =h.tool.price * h.count
                    zł)
                %td.taken_tool
                  .deleted
                    =h.created_at.to_formatted_s(:db)
              -else
                %td.taken_tool{style: "color: yellow;"}
                  Administrator
                %td.taken_tool
                  =h.tool_id
                %td.taken_tool
                  =h.tool.name
                %td.taken_tool
                  =h.count
                  (
                  =h.tool.price * h.count
                  zł)
                %td.taken_tool
                  =h.created_at.to_formatted_s(:db)
-else
  Brak
:javascript
  data_table_init_order = [4,'desc'];

magazyn/app/views/panel/index.html.haml
%table#group.row-border.hover
  %thead
    %tr
      %th Nazwa grupy
      %th Dodaj przedmiot
      %th Statystyka
  %tbody
    -@groups.each do |g|
      %tr
        %td
          =g.name
        %td
          %a{href: '#'}
            %span{"data-target" => "#myModal#{g.id}", "data-toggle" => "modal"}
              Dodaj
          .modal.fade{:id => "myModal#{g.id}", "aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
            .modal-dialog
              .modal-content
                .modal-header
                  %button.close{"data-dismiss" => "modal", :type => "button"}
                    %span{"aria-hidden" => "true"} ×
                    %span.sr-only Close
                  %h4#myModalLabel.modal-title 
                    Dodaj Przedmiot dla 
                    =g.name
                .modal-body
                  %table#modal-table.row-border.hover
                    %thead
                      %tr
                        %th Numer
                        %th Nazwa
                        %th Dostępnych
                        %th 
                      %tbody
                        -@tools.each do |t|
                          %tr
                            %td
                              =t.code
                            %td
                              =t.name
                            %td
                              =t.count
                            %td
                              =form_tag taken_tools_path, multipart: true do 
                                =number_field_tag :count, '', in: 1..99, step: '1'
                                =hidden_field_tag :tool_id, t.id
                                =hidden_field_tag :group_id, g.id
                                =submit_tag "+"
                .modal-footer
                  %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close
        %td
          stat

:javascript
  data_table_init_order = [0,'desc'];

magazyn/app/views/tools/edit.html.haml
=form_for @tool do |p|
  .form-group
    =p.label 'Kod'
    =p.text_field :code, class: 'form-control'
  .form-group
    =p.label 'Nazwa'
    =p.text_field :name, class: 'form-control'
  .form-group
    =p.label 'Ilosc'
    =p.number_field :count, in: 0..99, step: '1', class: 'form-control'
  .form-group
    =p.label 'Cena'
    =p.number_field :price, :step => 0.01, class: 'form-control'
  .form-group
    =submit_tag "Edytuj", class: "btn btn-primary"

magazyn/app/views/tools/index.html.haml
#show_add
  %a{href: '#'}
    Dodaj Przedmiot
.add
  =form_tag tools_path, multipart: true do 
    =fields_for @tool do |p|
      .row
        .col-lg-2

        .col-lg-4
          .form-group
            =p.label 'Kod'
            =p.text_field :code, class: 'form-control'
          .form-group
            =p.label 'Nazwa'
            =p.text_field :name, class: 'form-control'
        .col-lg-4
          .form-group
            =p.label 'Ilosc'
            =p.number_field :count, in: 0..99, step: '1', class: 'form-control'
          .form-group
            =p.label 'Cena'
            =p.number_field :price, :step => 0.01, class: 'form-control'
          .form-group
            =submit_tag "Dodaj", class: "btn btn-primary"
%table#group.row-border.hover
  %thead
    %tr
      %th Kod
      %th Nazwa
      %th Cena
      %th Ilosc
      %th 
      %th
  %tbody
    -@tools.each do |t|
      %tr
        %td
          =t.code
        %td
          =t.name
        %td
          =t.price
        %td
          =t.count
        %td
          =form_tag change_tools_admin_path, multipart: true do
            =submit_tag "-", name: "desc"
            =number_field_tag :count, '', in: 1..99, step: '1'
            =hidden_field_tag :tool_id, t.id
            =submit_tag "+", name: "desc"
        %td
          =link_to 'Edytuj', edit_tool_path(t.id)
          =link_to 'Usuń', tool_path(t.id), method: :delete, data: { confirm: "Napewno chcesz usunąć?" }

:javascript
  $(function(){
    add();
  })
:javascript
  data_table_init_order = [0,'asc'];

magazyn/app/views/users/edit.html.haml
=form_for @user do |p|
  .form-group
    =p.label 'Imie'
    =p.text_field :name, class: 'form-control'
  .form-group
    =p.label 'Nazwisko'
    =p.text_field :surname, class: 'form-control'
  .form-group
    =p.label 'Grupa'
    =p.select :group_id, options_from_collection_for_select(@groups, "id", "name", @user.group_id), {:include_blank => 'Brak'}, class: 'form-control'
  .form-group
    =submit_tag "Edytuj", class: "btn btn-primary"

magazyn/app/views/users/index.html.haml
-if params[:notice]
  .notice
    =params[:notice]

#show_add
  %a{href: '#'}
    Dodaj Użytkownika
.add
  =form_tag users_path, multipart: true do 
    =fields_for @user do |p|
      .row
        .col-lg-4

        .col-lg-4
          .form-group
            =p.label 'Imie'
            =p.text_field :name, class: 'form-control'
          .form-group
            =p.label 'Nazwisko'
            =p.text_field :surname, class: 'form-control'
          .form-group
            =p.label 'Grupa'
            =p.select :group_id, options_from_collection_for_select(@groups, "id", "name"),  {:include_blank => 'Brak'}, class: 'form-control'
          .form-group
            =submit_tag "Dodaj", class: "btn btn-primary"
%table#group.row-border.hover
  %thead
    %tr
      %th Kto
      %th Gdzie
      %th Data powstania
      %th 
  %tbody
    -@users.each do |u|
      %tr
        %td
          =u.name
          =u.surname
        %td
          -if u.group
            %div
              =u.group.name
          -else
            Brak
            %a{href: '#'}
              %span.plus{"data-target" => "#myModal#{u.id}", "data-toggle" => "modal"}
                +
            .modal.fade{:id => "myModal#{u.id}", "aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
              .modal-dialog
                .modal-content
                  .modal-header
                    %button.close{"data-dismiss" => "modal", :type => "button"}
                      %span{"aria-hidden" => "true"} ×
                      %span.sr-only Close
                    %h4#myModalLabel.modal-title 
                      Dodaj grupę
                      =u.name
                      =u.surname
                  .modal-body
                    %table#modal-table.row-border.hover
                      %thead
                        %tr
                          %th Nazwa
                          %th dodaj
                        %tbody
                          -@groups.each do |g|
                            %tr
                              %td
                                =g.name
                              %td
                                =link_to 'dodaj do', add_user_group_path(user: u.id, group: g.id), method: :post
                  .modal-footer
                    %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close
        %td
          =u.created_at.to_date
        %td
          =link_to 'Edytuj', edit_user_path(u.id)
          =link_to 'Usuń', user_path(u.id), method: :delete, data: { confirm: "Napewno chcesz usunąć?" }
:javascript
  $(function(){
    add();
  })

:javascript
  data_table_init_order = [0,'asc'];